version: '3.2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=dev_bugreporter
    - POSTGRES_USER=admin_dev
    - POSTGRES_PASSWORD=lemotdepasse
    ports:
    - "5432:5432"

volumes:
  db-data: {}